//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.10 at 07:19:48 PM CDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://modulo42.ebac.com/usuario", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ebac.modulo42.usuario;
